theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

title: "london bakery guide"
description: "Discover the best bakeries in London."
baseurl: "" # Leave empty for GitHub Pages
url: "https://thomassmith235.github.io" # Replace with your GitHub Pages URL

# Minimal Mistakes settings
author:
  name: "london bakery guide"
  avatar: "/assets/images/avatar.png" # Optional
  bio: "A guide to London's finest bakeries."
  location: "London, UK"

# Social media links (optional)
social:
  - name: "GitHub"
    url: "https://github.com/<your-username>"
    icon: "fab fa-github"

# Theme settings
minimal_mistakes_skin: "mint" # Change from "default" to "mint"
logo: /assets/images/logo.png

google_analytics: "UA-XXXXXXXXX-X"

collections:
  pages:
    output: true