remote_theme: "mmistakes/minimal-mistakes@4.26.2"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

title: "london bakery guide"
description: ""
baseurl: "" # Leave this empty for custom domains
url: "https://www.londonbakeries.co.uk" # Your custom domain


# Minimal Mistakes settings
author:
  name: "london bakery guide"
  avatar: "/assets/images/avatar.png" # Optional
  bio: "A guide to London's finest bakeries."
  location: "London, UK"

# Social media links (optional)
social:
  - name: "Instagram"
    url: "https://instagram.com/<your-username>"
    icon: "fab fa-github"

# Theme settings
minimal_mistakes_skin: "mint" # Change from "default" to "mint"
logo: /assets/images/logo.png

# Analytics settings
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-Q81QFXXHNF"
    anonymize_ip: true

collections:
  pages:
    output: true